name: Deploy using AWS SSM Send-Command

on:
  push:
    branches: [main]

jobs:
  something:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/park
          command: rm .env | touch .env | echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env | /bin/sh ./deploy.sh
          comment: Deploy the main branch
